module Calculate

using Dates,DivCalcMetrics

const OHLCVMetrics = 
[
    :std,
    :volatility,
    :william,
    :stochastic,
    :priceChange,
    :absPriceChange,
    :obv,
    :cci,
    :sma,
    :ema,
    :atr,
    :upperWickChange,
    :lowerWickChange,
    :upperWickSTD,
    :lowerWickSTD,
    :watr
]

const FocusedMetrics = 
[

    :priceChangeEMA5m,
    :priceChangeEMA15m,
    :priceChangeEMA30m,
    :priceChangeEMA1h,
    :priceChangeEMA2h,
    :priceChangeEMA4h,
    :priceChangeEMA8h,
    :priceChangeEMA12h,
    :priceChangeEMA16h,
    :priceChangeEMA24h,
    :priceChangeEMA48h,
    :absPriceChangeEMA5m,
    :absPriceChangeEMA15m,
    :absPriceChangeEMA30m,
    :absPriceChangeEMA1h,
    :absPriceChangeEMA2h,
    :absPriceChangeEMA4h,
    :absPriceChangeEMA8h,
    :absPriceChangeEMA12h,
    :absPriceChangeEMA16h,
    :absPriceChangeEMA24h,
    :absPriceChangeEMA48h,
    :pcDEMA5m,
    :pcDEMA15m,
    :pcDEMA30m,
    :pcDEMA1h,
    :pcDEMA2h,
    :pcDEMA4h,
    :pcDEMA8h,
    :pcDEMA12h, 
    :pcDEMA16h, 
    :pcDEMA24h, 
    :pcDEMA48h, 
    :apcDEMA5m, 
    :apcDEMA15m, 
    :apcDEMA30m, 
    :apcDEMA1h, 
    :apcDEMA2h, 
    :apcDEMA4h, 
    :apcDEMA8h, 
    :apcDEMA12h,
    :apcDEMA16h,
    :apcDEMA24h,
    :apcDEMA48h,
    :tsi5m,
    :tsi15m,
    :tsi30m,
    :tsi1h,
    :tsi2h,
    :tsi4h,
    :tsi8h,
    :tsi12h,
    :tsi16h,
    :tsi24h,
    :tsi48h,
    :diffOBV,
    :emaOBV5m, 
    :emaOBV15m, 
    :emaOBV30m, 
    :emaOBV1h, 
    :emaOBV2h,
    :emaOBV4h,
    :emaOBV8h,
    :emaOBV12h,
    :emaOBV16h,
    :emaOBV24h,
    :emaOBV48h,
    :macd5m,
    :macd15m,
    :macd30m,
    :macd1h,
    :macd2h,
    :macd4h,
    :macd8h,
    :macd12h,
    :macd16h,
    :signalLine5m15m,
    :signalLine5m30m,
    :signalLine5m1h,
    :signalLine5m2h,
    :signalLine5m8h,
    :signalLine5m16h,
    :signalLine5m24h,
    :signalLine15m30m,
    :signalLine15m1h,
    :signalLine15m2h,
    :signalLine15m8h,
    :signalLine15m16h,
    :signalLine15m24h,
    :signalLine30m1h,
    :signalLine30m2h,
    :signalLine30m8h,
    :signalLine30m16h,
    :signalLine30m24h,
    :signalLine1h2h,
    :signalLine1h8h,
    :signalLine1h16h, 
    :signalLine1h24h, 
    :signalLine2h4h,
    :signalLine2h8h,
    :signalLine2h16h, 
    :signalLine2h24h, 
    :smaSTD5m,
    :smaSTD15m,
    :smaSTD30m,
    :smaSTD1h,
    :smaSTD2h,
    :smaSTD4h,
    :smaSTD8h,
    :smaSTD12h, 
    :smaSTD16h,
    :smaSTD24h,
    :emaChange5m,
    :emaChange15m,
    :emaChange30m,
    :emaChange1h,
    :emaChange4h,
    :emaChange8h,
    :emaChange12h,
    :emaChange16h,
    :emaChange24h,
    :emaChange48h,
    :emaSTD5m,
    :emaSTD15m,
    :emaSTD30m,
    :emaSTD1h,
    :emaSTD2h,
    :emaSTD4h,
    :emaSTD8h,
    :emaSTD12h,
    :emaSTD16h,
    :emaSTD24h,
    :emaSTD48h,
    :emaema5m,
    :emaema15m,
    :emaema30m,
    :emaema1h,
    :emaema2h,
    :emaema4h,
    :emaema8h,
    :emaema12h,
    :emaema16h,
    :emaema24h,
    :emaema48h,
    :dema5m,
    :dema15m,
    :dema30m,
    :dema1h,
    :dema2h,
    :dema4h,
    :dema8h,
    :dema12h,
    :dema16h,
    :dema24h,
    :dema48h,
    :ppo5m,
    :ppo15m,
    :ppo30m,
    :ppo1h,
    :ppo2h,
    :ppo4h,
    :ppo8h,
    :ppo12h,
    :ppo16h,
    :ppo24h,
    :stdATR5m,
    :stdATR15m,
    :stdATR30m,
    :stdATR1h,
    :stdATR2h,
    :stdATR4h,
    :stdATR8h,
    :stdATR12h,
    :stdATR16h,
    :stdATR24h,
    :diffATR5m,
    :diffATR15m,
    :diffATR30m,
    :diffATR1h,
    :diffATR2h,
    :diffATR4h,
    :diffATR8h,
    :diffATR12h, 
    :diffATR16h,
    :diffATR24h,
    :diffATR48h,
    :upperWickChangeEMA5m,
    :upperWickChangeEMA15m,
    :upperWickChangeEMA30m,
    :upperWickChangeEMA1h,
    :upperWickChangeEMA2h,
    :upperWickChangeEMA4h,
    :upperWickChangeEMA8h,
    :upperWickChangeEMA12h,
    :lowerWickChangeEMA5m,
    :lowerWickChangeEMA15m,
    :lowerWickChangeEMA30m,
    :lowerWickChangeEMA1h,
    :lowerWickChangeEMA2h,
    :lowerWickChangeEMA4h,
    :lowerWickChangeEMA8h,
    :lowerWickChangeEMA12h,
    :lowerWickChangeEMA16h,
    :lowerWickChangeEMA24h,
    :lowerWickChangeEMA48h,
    :stdWATR5m,
    :stdWATR15m,
    :stdWATR30m,
    :stdWATR1h,
    :stdWATR2h,
    :stdWATR4h,
    :stdWATR8h,
    :stdWATR12h,
    :stdWATR16h,
    :stdWATR24h,
    :stdWATR48h
]

CalculatedMetrics1m :: Dict = Dict()

mutable struct Focused1m

    timestamp :: Dates.DateTime
    metrics:: Dict

    Focused1m(metrics) = new(Dates.now(),metrics)
end

function calculate1m(id::Int,data)

    global CalculatedMetrics1m

    ohlcv1mSegmented = create_segment(data[:ohlcv])
    focused1mSegmented = create_segment(data[:data1m])

    for metric in keys(CalculatedMetrics1m[id].metrics)

        if metric in OHLCVMetrics
            calculate!(CalculatedMetrics1m[id].metrics[metric],ohlcv1mSegmented)
        elseif metric in FocusedMetrics
            calculate!(CalculatedMetrics1m[id].metrics[metric],focused1mSegmented)
        else
            error("incorrect metric used ",metric)
        end
    end 

    CalculatedMetrics1m[id].timestamp = Dates.now()

    return CalculatedMetrics1m[id] 
    # used for testing
end

function __init__()

    ids = [1]
    global CalculatedMetrics1m
    global CalculatedMetrics5m

    for id in ids
        
        push!(CalculatedMetrics1m, id => Focused1m(Dict(
                :std => STD(),
                :volatility => Volatility(),
                :william => William(),
                :stochastic => Stochastic(),
                :priceChange => PriceChange(),
                :priceChangeEMA5m => PriceChangeEMA5m(),
                :priceChangeEMA15m => PriceChangeEMA15m(),
                :priceChangeEMA30m => PriceChangeEMA30m(),
                :priceChangeEMA1h => PriceChangeEMA1h(),
                :priceChangeEMA2h => PriceChangeEMA2h(),
                :priceChangeEMA4h => PriceChangeEMA4h(),
                :priceChangeEMA8h => PriceChangeEMA8h(),
                :priceChangeEMA12h => PriceChangeEMA12h(),
                :priceChangeEMA16h => PriceChangeEMA16h(),
                :priceChangeEMA24h => PriceChangeEMA24h(),
                :priceChangeEMA48h => PriceChangeEMA48h(),
                :absPriceChange => AbsPriceChange(),
                :absPriceChangeEMA5m => AbsPriceChangeEMA5m(),
                :absPriceChangeEMA15m => AbsPriceChangeEMA15m(),
                :absPriceChangeEMA30m => AbsPriceChangeEMA30m(),
                :absPriceChangeEMA1h => AbsPriceChangeEMA1h(),
                :absPriceChangeEMA2h => AbsPriceChangeEMA2h(),
                :absPriceChangeEMA4h => AbsPriceChangeEMA4h(),
                :absPriceChangeEMA8h => AbsPriceChangeEMA8h(),
                :absPriceChangeEMA12h => AbsPriceChangeEMA12h(),
                :absPriceChangeEMA16h => AbsPriceChangeEMA16h(),
                :absPriceChangeEMA24h => AbsPriceChangeEMA24h(),
                :absPriceChangeEMA48h => AbsPriceChangeEMA48h(),
                :pcDEMA5m => PCDEMA5m(),
                :pcDEMA15m => PCDEMA15m(),
                :pcDEMA30m => PCDEMA30m(),
                :pcDEMA1h => PCDEMA1h(),
                :pcDEMA2h => PCDEMA2h(),
                :pcDEMA4h => PCDEMA4h(),
                :pcDEMA8h => PCDEMA8h(),
                :pcDEMA12h => PCDEMA12h(),
                :pcDEMA16h => PCDEMA16h(),
                :pcDEMA24h => PCDEMA24h(),
                :pcDEMA48h => PCDEMA48h(),
                :apcDEMA5m => APCDEMA5m(),
                :apcDEMA15m => APCDEMA15m(),
                :apcDEMA30m => APCDEMA30m(),
                :apcDEMA1h => APCDEMA1h(),
                :apcDEMA2h => APCDEMA2h(),
                :apcDEMA4h => APCDEMA4h(),
                :apcDEMA8h => APCDEMA8h(),
                :apcDEMA12h => APCDEMA12h(),
                :apcDEMA16h => APCDEMA16h(),
                :apcDEMA24h => APCDEMA24h(),
                :apcDEMA48h => APCDEMA48h(),
                :tsi5m => TSI5m(),
                :tsi15m => TSI15m(),
                :tsi30m => TSI30m(),
                :tsi1h => TSI1h(),
                :tsi2h => TSI2h(),
                :tsi4h => TSI4h(),
                :tsi8h => TSI8h(),
                :tsi12h => TSI12h(),
                :tsi16h => TSI16h(),
                :tsi24h => TSI24h(),
                :tsi48h => TSI48h(),
                :obv => OBV(),
                :diffOBV => DiffOBV(),
                :emaOBV5m => EMAOBV5m(),
                :emaOBV15m => EMAOBV15m(),
                :emaOBV30m => EMAOBV30m(),
                :emaOBV1h => EMAOBV1h(),
                :emaOBV2h => EMAOBV2h(),
                :emaOBV4h => EMAOBV4h(),
                :emaOBV8h => EMAOBV8h(),
                :emaOBV12h => EMAOBV12h(),
                :emaOBV16h => EMAOBV16h(),
                :emaOBV24h => EMAOBV24h(),
                :emaOBV48h => EMAOBV48h(),
                :cci => CCI(),
                :macd5m => MACD5m(),
                :macd15m => MACD15m(),
                :macd30m => MACD30m(),
                :macd1h => MACD1h(),
                :macd2h => MACD2h(),
                :macd4h => MACD4h(),
                :macd8h => MACD8h(),
                :macd12h => MACD12h(),
                :macd16h => MACD16h(),
                :signalLine5m15m => SignalLine5m15m(),
                :signalLine5m30m => SignalLine5m30m(),
                :signalLine5m1h => SignalLine5m1h(),
                :signalLine5m2h => SignalLine5m2h(),
                :signalLine5m8h => SignalLine5m8h(),
                :signalLine5m16h => SignalLine5m16h(),
                :signalLine5m24h => SignalLine5m24h(),
                :signalLine15m30m => SignalLine15m30m(),
                :signalLine15m1h => SignalLine15m1h(),
                :signalLine15m2h => SignalLine15m2h(),
                :signalLine15m8h => SignalLine15m8h(),
                :signalLine15m16h => SignalLine15m16h(),
                :signalLine15m24h => SignalLine15m24h(),
                :signalLine30m1h => SignalLine30m1h(),
                :signalLine30m2h => SignalLine30m2h(),
                :signalLine30m8h => SignalLine30m8h(),
                :signalLine30m16h => SignalLine30m16h(),
                :signalLine30m24h => SignalLine30m24h(),
                :signalLine1h2h => SignalLine1h2h(),
                :signalLine1h8h => SignalLine1h8h(),
                :signalLine1h16h => SignalLine1h16h(),
                :signalLine1h24h => SignalLine1h24h(),
                :signalLine2h4h => SignalLine2h4h(),
                :signalLine2h8h => SignalLine2h8h(),
                :signalLine2h16h => SignalLine2h16h(),
                :signalLine2h24h => SignalLine2h24h(), 
                :sma => SMA(),
                :smaSTD5m => SMASTD5m(),
                :smaSTD15m => SMASTD15m(),
                :smaSTD30m => SMASTD30m(),
                :smaSTD1h => SMASTD1h(),
                :smaSTD2h => SMASTD2h(),
                :smaSTD4h => SMASTD4h(),
                :smaSTD8h => SMASTD8h(),
                :smaSTD12h => SMASTD12h(),
                :smaSTD16h => SMASTD16h(),
                :smaSTD24h => SMASTD24h(),
                :ema => EMA(),
                :emaChange5m => EMAChange5m(),
                :emaChange15m => EMAChange15m(),
                :emaChange30m => EMAChange30m(),
                :emaChange1h => EMAChange1h(),
                :emaChange4h => EMAChange4h(),
                :emaChange8h => EMAChange8h(),
                :emaChange12h => EMAChange12h(),
                :emaChange16h => EMAChange16h(),
                :emaChange24h => EMAChange24h(),
                :emaChange48h => EMAChange48h(),
                :emaSTD5m => EMASTD5m(),
                :emaSTD15m => EMASTD15m(),
                :emaSTD30m => EMASTD30m(),
                :emaSTD1h => EMASTD1h(),
                :emaSTD2h => EMASTD2h(),
                :emaSTD4h => EMASTD4h(),
                :emaSTD8h => EMASTD8h(),
                :emaSTD24h => EMASTD24h(),
                :emaSTD48h => EMASTD48h(),
                :emaema5m => EMAEMA5m(),
                :emaema15m => EMAEMA15m(),
                :emaema30m => EMAEMA30m(),
                :emaema1h => EMAEMA1h(),
                :emaema2h => EMAEMA2h(),
                :emaema4h => EMAEMA4h(),
                :emaema8h => EMAEMA8h(),
                :emaema12h => EMAEMA12h(),
                :emaema16h => EMAEMA16h(),
                :emaema24h => EMAEMA24h(),
                :emaema48h => EMAEMA48h(),
                :dema5m => DEMA5m(),
                :dema15m => DEMA15m(),
                :dema30m => DEMA30m(),
                :dema1h => DEMA1h(),
                :dema2h => DEMA2h(),
                :dema4h => DEMA4h(),
                :dema8h => DEMA8h(),
                :dema12h => DEMA12h(),
                :dema16h => DEMA16h(),
                :dema24h => DEMA24h(),
                :dema48h => DEMA48h(),
                :ppo5m => PPO5m(),
                :ppo15m => PPO15m(),
                :ppo30m => PPO30m(),
                :ppo1h => PPO1h(),
                :ppo2h => PPO2h(),
                :ppo4h => PPO4h(),
                :ppo8h => PPO8h(),
                :ppo12h => PPO12h(),
                :ppo16h => PPO16h(),
                :ppo24h => PPO24h(),
                :atr => ATR(),
                :stdATR5m => STDATR5m(),
                :stdATR15m => STDATR15m(),
                :stdATR30m => STDATR30m(),
                :stdATR1h => STDATR1h(),
                :stdATR2h => STDATR2h(),
                :stdATR4h => STDATR4h(),
                :stdATR8h => STDATR8h(),
                :stdATR12h => STDATR12h(),
                :stdATR16h => STDATR16h(),
                :stdATR24h => STDATR24h(),
                :upperWickChange => UpperWickChange(),
                :lowerWickChange => LowerWickChange(),
                :upperWickChangeEMA5m => UpperWickChangeEMA5m(),
                :upperWickChangeEMA15m => UpperWickChangeEMA15m(),
                :upperWickChangeEMA30m => UpperWickChangeEMA30m(),
                :upperWickChangeEMA1h => UpperWickChangeEMA1h(),
                :upperWickChangeEMA2h => UpperWickChangeEMA2h(),
                :upperWickChangeEMA4h => UpperWickChangeEMA4h(),
                :upperWickChangeEMA8h => UpperWickChangeEMA8h(),
                :upperWickChangeEMA12h => UpperWickChangeEMA12h(),
                :lowerWickChangeEMA5m => LowerWickChangeEMA5m(),
                :lowerWickChangeEMA15m => LowerWickChangeEMA15m(),
                :lowerWickChangeEMA30m => LowerWickChangeEMA30m(),
                :lowerWickChangeEMA1h => LowerWickChangeEMA1h(),
                :lowerWickChangeEMA2h => LowerWickChangeEMA2h(),
                :lowerWickChangeEMA4h => LowerWickChangeEMA4h(),
                :lowerWickChangeEMA8h => LowerWickChangeEMA8h(),
                :lowerWickChangeEMA12h => LowerWickChangeEMA12h(),
                :lowerWickChangeEMA16h => LowerWickChangeEMA16h(),
                :lowerWickChangeEMA24h => LowerWickChangeEMA24h(),
                :lowerWickChangeEMA48h => LowerWickChangeEMA48h(),
                :upperWickSTD => UpperWickSTD(),
                :lowerWickSTD => LowerWickSTD(),
                :watr => WATR(),
                :stdWATR5m => STDWATR5m(),
                :stdWATR15m => STDWATR15m(),
                :stdWATR30m => STDWATR30m(),
                :stdWATR1h => STDWATR1h(),
                :stdWATR2h => STDWATR2h(),
                :stdWATR4h => STDWATR4h(),
                :stdWATR8h => STDWATR8h(),
                :stdWATR12h => STDWATR12h(),
                :stdWATR16h => STDWATR16h(),
                :stdWATR24h => STDWATR24h(),
                :stdWATR48h => STDWATR48h()
                ))
        )        
    end

end

end