# include("Calculate.jl")

# import .Calculate

# using DataFrames, Decimals, Dates, Test, Statistics, DivCalcMetrics, CSV

# ohlcvData = CSV.read("bch_ohlcv1m.csv",DataFrame,stringtype=String)
# ohlcvData[!,:timestamp] = Dates.DateTime.(ohlcvData[!,:timestamp],"yyyy-mm-dd HH:MM:SS")
# ohlcvData = sort(ohlcvData,[:timestamp];rev=true)

# endN = nrow(ohlcvData)-2

# calculated1m = calcframe()

# for ohlcvPos in endN:-1:1

#     if ohlcvPos+500 > endN
#         ohlcvDataTemp = ohlcvData[ohlcvPos:end,:]
#     else
#         ohlcvDataTemp = ohlcvData[ohlcvPos:ohlcvPos+500,:]
#     end

#     startTime = first(ohlcvDataTemp).timestamp

#     focusedData = sort(calculated1m,[:timestamp],rev=true)

#     data = Dict(
#     :ohlcv => ohlcvDataTemp,
#     :data1m => focusedData
#     )

#     calc = Calculate.calculate1m(21,data)
#     metrics = calc.metrics

#     push!(calculated1m,
#         [21,
#         startTime, 
#         Dates.now(),

#         metrics[:std].t5m, 
#         metrics[:std].t10m,
#         metrics[:std].t15m,
#         metrics[:std].t30m,
#         metrics[:std].t1h,
#         metrics[:std].t2h,
#         metrics[:std].t4h,
#         metrics[:std].t8h,

#         metrics[:volatility].t5m, 
#         metrics[:volatility].t10m,
#         metrics[:volatility].t15m,
#         metrics[:volatility].t30m,
#         metrics[:volatility].t1h,
#         metrics[:volatility].t2h,
#         metrics[:volatility].t4h,
#         metrics[:volatility].t8h,

#         metrics[:william].t5m,
#         metrics[:william].t10m,
#         metrics[:william].t15m,
#         metrics[:william].t30m,
#         metrics[:william].t1h,
#         metrics[:william].t2h,
#         metrics[:william].t4h,
#         metrics[:william].t8h,

#         metrics[:stochastic].t5m,
#         metrics[:stochastic].t10m,
#         metrics[:stochastic].t15m,
#         metrics[:stochastic].t30m,
#         metrics[:stochastic].t1h,
#         metrics[:stochastic].t2h,
#         metrics[:stochastic].t4h,
#         metrics[:stochastic].t8h,

#         metrics[:tsi5m].t5m,
#         metrics[:tsi5m].t10m,
#         metrics[:tsi5m].t15m,
#         metrics[:tsi5m].t30m,
#         metrics[:tsi5m].t8h,
#         metrics[:tsi30m].t5m,
#         metrics[:tsi30m].t30m,
#         metrics[:tsi30m].t8h,
#         metrics[:tsi8h].t5m,
#         metrics[:tsi8h].t30m,
#         metrics[:tsi8h].t8h,

#         metrics[:obv].value,
        
#         metrics[:diffOBV].t5m,
#         metrics[:diffOBV].t10m,
#         metrics[:diffOBV].t15m,
#         metrics[:diffOBV].t30m,
#         metrics[:diffOBV].t1h,
#         metrics[:diffOBV].t2h,
#         metrics[:diffOBV].t4h,
#         metrics[:diffOBV].t8h,

#         metrics[:emaOBV5m].t5m,
#         metrics[:emaOBV5m].t10m,
#         metrics[:emaOBV5m].t15m,
#         metrics[:emaOBV5m].t30m,
#         metrics[:emaOBV5m].t1h,
#         metrics[:emaOBV5m].t2h,
#         metrics[:emaOBV5m].t4h,
#         metrics[:emaOBV5m].t8h,
#         metrics[:emaOBV30m].t5m,
#         metrics[:emaOBV30m].t10m,
#         metrics[:emaOBV30m].t15m,
#         metrics[:emaOBV30m].t30m,
#         metrics[:emaOBV30m].t1h,
#         metrics[:emaOBV30m].t2h,
#         metrics[:emaOBV30m].t4h,
#         metrics[:emaOBV30m].t8h,
#         metrics[:emaOBV8h].t5m,
#         metrics[:emaOBV8h].t10m,
#         metrics[:emaOBV8h].t15m,
#         metrics[:emaOBV8h].t30m,
#         metrics[:emaOBV8h].t1h,
#         metrics[:emaOBV8h].t2h,
#         metrics[:emaOBV8h].t4h,
#         metrics[:emaOBV8h].t8h,

#         metrics[:cci].t5m,
#         metrics[:cci].t10m,
#         metrics[:cci].t15m,
#         metrics[:cci].t30m,
#         metrics[:cci].t1h,
#         metrics[:cci].t2h,
#         metrics[:cci].t4h,
#         metrics[:cci].t8h,

#         metrics[:macd].t5m_10m,
#         metrics[:macd].t5m_15m,
#         metrics[:macd].t5m_30m,
#         metrics[:macd].t5m_1h,
#         metrics[:macd].t5m_2h,
#         metrics[:macd].t5m_4h,
#         metrics[:macd].t5m_8h,
#         metrics[:macd].t30m_8h,

#         metrics[:signalLine5m10m].t5m,
#         metrics[:signalLine5m10m].t10m,
#         metrics[:signalLine5m15m].t5m,
#         metrics[:signalLine5m15m].t10m,
#         metrics[:signalLine5m30m].t5m,
#         metrics[:signalLine5m30m].t30m,
#         metrics[:signalLine5m30m].t8h,
#         metrics[:signalLine5m8h].t5m,
#         metrics[:signalLine5m8h].t30m,
#         metrics[:signalLine5m8h].t8h,
#         metrics[:signalLine30m8h].t5m,
#         metrics[:signalLine30m8h].t30m,
#         metrics[:signalLine30m8h].t8h,

#         metrics[:sma].t5m,
#         metrics[:sma].t10m,
#         metrics[:sma].t15m,
#         metrics[:sma].t30m,
#         metrics[:sma].t1h,
#         metrics[:sma].t2h,
#         metrics[:sma].t4h,
#         metrics[:sma].t8h,

#         metrics[:smaChange5m].t5m,
#         metrics[:smaChange5m].t10m,
#         metrics[:smaChange5m].t15m,
#         metrics[:smaChange5m].t30m,
#         metrics[:smaChange5m].t1h,
#         metrics[:smaChange5m].t2h,
#         metrics[:smaChange5m].t4h,
#         metrics[:smaChange5m].t8h,

#         metrics[:smaChange30m].t5m,
#         metrics[:smaChange30m].t10m,
#         metrics[:smaChange30m].t15m,
#         metrics[:smaChange30m].t30m,
#         metrics[:smaChange30m].t1h,
#         metrics[:smaChange30m].t2h,
#         metrics[:smaChange30m].t4h,
#         metrics[:smaChange30m].t8h,

#         metrics[:smaSTD5m].t5m,
#         metrics[:smaSTD5m].t10m,
#         metrics[:smaSTD5m].t15m,
#         metrics[:smaSTD5m].t30m,
#         metrics[:smaSTD5m].t1h,
#         metrics[:smaSTD5m].t2h,
#         metrics[:smaSTD5m].t4h,
#         metrics[:smaSTD5m].t8h,

#         metrics[:smaSTD30m].t5m,
#         metrics[:smaSTD30m].t10m,
#         metrics[:smaSTD30m].t15m,
#         metrics[:smaSTD30m].t30m,
#         metrics[:smaSTD30m].t1h,
#         metrics[:smaSTD30m].t2h,
#         metrics[:smaSTD30m].t4h,
#         metrics[:smaSTD30m].t8h,

#         metrics[:ema].t5m,
#         metrics[:ema].t10m,
#         metrics[:ema].t15m,
#         metrics[:ema].t30m,
#         metrics[:ema].t1h,
#         metrics[:ema].t2h,
#         metrics[:ema].t4h,
#         metrics[:ema].t8h,

#         metrics[:emaChange5m].t5m,
#         metrics[:emaChange5m].t10m,
#         metrics[:emaChange5m].t15m,
#         metrics[:emaChange5m].t30m,
#         metrics[:emaChange5m].t1h,
#         metrics[:emaChange5m].t2h,
#         metrics[:emaChange5m].t4h,
#         metrics[:emaChange5m].t8h,

#         metrics[:emaChange30m].t5m,
#         metrics[:emaChange30m].t10m,
#         metrics[:emaChange30m].t15m,
#         metrics[:emaChange30m].t30m,
#         metrics[:emaChange30m].t1h,
#         metrics[:emaChange30m].t2h,
#         metrics[:emaChange30m].t4h,
#         metrics[:emaChange30m].t8h,

#         metrics[:emaSTD5m].t5m,
#         metrics[:emaSTD5m].t10m,
#         metrics[:emaSTD5m].t15m,
#         metrics[:emaSTD5m].t30m,
#         metrics[:emaSTD5m].t1h,
#         metrics[:emaSTD5m].t2h,
#         metrics[:emaSTD5m].t4h,
#         metrics[:emaSTD5m].t8h,

#         metrics[:emaSTD30m].t5m,
#         metrics[:emaSTD30m].t10m,
#         metrics[:emaSTD30m].t15m,
#         metrics[:emaSTD30m].t30m,
#         metrics[:emaSTD30m].t1h,
#         metrics[:emaSTD30m].t2h,
#         metrics[:emaSTD30m].t4h,
#         metrics[:emaSTD30m].t8h,

#         metrics[:dema5m].t5m,
#         metrics[:dema5m].t30m,
#         metrics[:dema5m].t8h,
#         metrics[:dema30m].t5m,
#         metrics[:dema30m].t30m,
#         metrics[:dema30m].t8h,
#         metrics[:dema8h].t5m,
#         metrics[:dema8h].t30m,
#         metrics[:dema8h].t8h,

#         metrics[:ppo].t5m_10m,
#         metrics[:ppo].t5m_15m,
#         metrics[:ppo].t5m_30m,
#         metrics[:ppo].t5m_1h,
#         metrics[:ppo].t5m_2h,
#         metrics[:ppo].t5m_4h,
#         metrics[:ppo].t5m_8h,
#         metrics[:ppo].t30m_8h,

#         metrics[:atr].t5m,
#         metrics[:atr].t10m,
#         metrics[:atr].t15m,
#         metrics[:atr].t30m,
#         metrics[:atr].t1h,
#         metrics[:atr].t2h,
#         metrics[:atr].t4h,
#         metrics[:atr].t8h,

#         metrics[:stdATR5m].t5m,
#         metrics[:stdATR5m].t10m,
#         metrics[:stdATR5m].t15m,
#         metrics[:stdATR5m].t30m,
#         metrics[:stdATR5m].t1h,
#         metrics[:stdATR5m].t2h,
#         metrics[:stdATR5m].t4h,
#         metrics[:stdATR5m].t8h,
        
#         metrics[:stdATR30m].t5m,
#         metrics[:stdATR30m].t10m,
#         metrics[:stdATR30m].t15m,
#         metrics[:stdATR30m].t30m,
#         metrics[:stdATR30m].t1h,
#         metrics[:stdATR30m].t2h,
#         metrics[:stdATR30m].t4h,
#         metrics[:stdATR30m].t8h,
        
#         metrics[:stdATR8h].t5m,
#         metrics[:stdATR8h].t30m,
#         metrics[:stdATR8h].t8h,

#         metrics[:diffATR5m].t5m,
#         metrics[:diffATR5m].t30m,
#         metrics[:diffATR5m].t1h,
#         metrics[:diffATR5m].t2h,
#         metrics[:diffATR5m].t4h,
#         metrics[:diffATR5m].t8h,
#         metrics[:diffATR30m].t5m,
#         metrics[:diffATR30m].t30m,
#         metrics[:diffATR30m].t1h,
#         metrics[:diffATR30m].t2h,
#         metrics[:diffATR30m].t4h,
#         metrics[:diffATR30m].t8h,
#         metrics[:diffATR8h].t5m,
#         metrics[:diffATR8h].t30m,
#         metrics[:diffATR8h].t1h,
#         metrics[:diffATR8h].t2h,
#         metrics[:diffATR8h].t4h,
#         metrics[:diffATR8h].t8h,

#         metrics[:emaDiffATR5m].t5m,
#         metrics[:emaDiffATR5m].t30m,
#         metrics[:emaDiffATR5m].t1h,
#         metrics[:emaDiffATR5m].t2h,
#         metrics[:emaDiffATR5m].t4h,
#         metrics[:emaDiffATR5m].t8h,
#         metrics[:emaDiffATR30m].t5m,
#         metrics[:emaDiffATR30m].t30m,
#         metrics[:emaDiffATR30m].t1h,
#         metrics[:emaDiffATR30m].t2h,
#         metrics[:emaDiffATR30m].t4h,
#         metrics[:emaDiffATR30m].t8h,
#         metrics[:emaDiffATR8h].t5m,
#         metrics[:emaDiffATR8h].t30m,
#         metrics[:emaDiffATR8h].t1h,
#         metrics[:emaDiffATR8h].t2h,
#         metrics[:emaDiffATR8h].t4h,
#         metrics[:emaDiffATR8h].t8h,

#         metrics[:priceChange].t5m,
#         metrics[:priceChange].t10m,
#         metrics[:priceChange].t15m,
#         metrics[:priceChange].t30m,
#         metrics[:priceChange].t1h,
#         metrics[:priceChange].t2h,
#         metrics[:priceChange].t4h,
#         metrics[:priceChange].t8h,

#         metrics[:priceChangeEMA5m].t5m,
#         metrics[:priceChangeEMA5m].t10m,
#         metrics[:priceChangeEMA5m].t15m,
#         metrics[:priceChangeEMA5m].t30m,
#         metrics[:priceChangeEMA5m].t1h,
#         metrics[:priceChangeEMA5m].t2h,
#         metrics[:priceChangeEMA5m].t4h,
#         metrics[:priceChangeEMA5m].t8h,
#         metrics[:priceChangeEMA30m].t5m,
#         metrics[:priceChangeEMA30m].t10m,
#         metrics[:priceChangeEMA30m].t15m,
#         metrics[:priceChangeEMA30m].t30m,
#         metrics[:priceChangeEMA30m].t1h,
#         metrics[:priceChangeEMA30m].t2h,
#         metrics[:priceChangeEMA30m].t4h,
#         metrics[:priceChangeEMA30m].t8h,
#         metrics[:priceChangeEMA8h].t5m,
#         metrics[:priceChangeEMA8h].t10m,
#         metrics[:priceChangeEMA8h].t15m,
#         metrics[:priceChangeEMA8h].t30m,
#         metrics[:priceChangeEMA8h].t1h,
#         metrics[:priceChangeEMA8h].t2h,
#         metrics[:priceChangeEMA8h].t4h,
#         metrics[:priceChangeEMA8h].t8h,

#         metrics[:absPriceChange].t5m,
#         metrics[:absPriceChange].t10m,
#         metrics[:absPriceChange].t15m,
#         metrics[:absPriceChange].t30m,
#         metrics[:absPriceChange].t1h,
#         metrics[:absPriceChange].t2h,
#         metrics[:absPriceChange].t4h,
#         metrics[:absPriceChange].t8h,

#         metrics[:absPriceChangeEMA5m].t5m,
#         metrics[:absPriceChangeEMA5m].t10m,
#         metrics[:absPriceChangeEMA5m].t15m,
#         metrics[:absPriceChangeEMA5m].t30m,
#         metrics[:absPriceChangeEMA5m].t1h,
#         metrics[:absPriceChangeEMA5m].t2h,
#         metrics[:absPriceChangeEMA5m].t4h,
#         metrics[:absPriceChangeEMA5m].t8h,      
#         metrics[:absPriceChangeEMA30m].t5m,
#         metrics[:absPriceChangeEMA30m].t10m,
#         metrics[:absPriceChangeEMA30m].t15m,
#         metrics[:absPriceChangeEMA30m].t30m,
#         metrics[:absPriceChangeEMA30m].t1h,
#         metrics[:absPriceChangeEMA30m].t2h,
#         metrics[:absPriceChangeEMA30m].t4h,
#         metrics[:absPriceChangeEMA30m].t8h,
#         metrics[:absPriceChangeEMA8h].t5m,
#         metrics[:absPriceChangeEMA8h].t10m,
#         metrics[:absPriceChangeEMA8h].t15m,
#         metrics[:absPriceChangeEMA8h].t30m,
#         metrics[:absPriceChangeEMA8h].t1h,
#         metrics[:absPriceChangeEMA8h].t2h,
#         metrics[:absPriceChangeEMA8h].t4h,
#         metrics[:absPriceChangeEMA8h].t8h,

#         metrics[:pcDEMA5m].t5m,
#         metrics[:pcDEMA5m].t10m,
#         metrics[:pcDEMA5m].t15m,
#         metrics[:pcDEMA5m].t30m,
#         metrics[:pcDEMA5m].t8h,
#         metrics[:pcDEMA30m].t5m,
#         metrics[:pcDEMA30m].t30m,
#         metrics[:pcDEMA30m].t8h,
#         metrics[:pcDEMA8h].t5m,
#         metrics[:pcDEMA8h].t30m,
#         metrics[:pcDEMA8h].t8h,
        
#         metrics[:apcDEMA5m].t5m,
#         metrics[:apcDEMA5m].t10m,
#         metrics[:apcDEMA5m].t15m,
#         metrics[:apcDEMA5m].t30m,
#         metrics[:apcDEMA5m].t1h,
#         metrics[:apcDEMA5m].t2h,
#         metrics[:apcDEMA5m].t4h,
#         metrics[:apcDEMA5m].t8h,
        
#         metrics[:apcDEMA30m].t5m,
#         metrics[:apcDEMA30m].t10m,
#         metrics[:apcDEMA30m].t15m,
#         metrics[:apcDEMA30m].t30m,
#         metrics[:apcDEMA30m].t1h,
#         metrics[:apcDEMA30m].t2h,
#         metrics[:apcDEMA30m].t4h,
#         metrics[:apcDEMA30m].t8h,
        
#         metrics[:apcDEMA8h].t5m,
#         metrics[:apcDEMA8h].t30m,
#         metrics[:apcDEMA8h].t8h,

#         metrics[:emaema5m].t5m,
#         metrics[:emaema5m].t30m,
#         metrics[:emaema5m].t8h,
#         metrics[:emaema30m].t5m,
#         metrics[:emaema30m].t30m,
#         metrics[:emaema30m].t8h,
#         metrics[:emaema8h].t5m,
#         metrics[:emaema8h].t30m,
#         metrics[:emaema8h].t8h,
        
#         metrics[:upperWickChange].t5m,
#         metrics[:upperWickChange].t10m,
#         metrics[:upperWickChange].t15m,
#         metrics[:upperWickChange].t30m,
#         metrics[:upperWickChange].t1h,
#         metrics[:upperWickChange].t2h,
#         metrics[:upperWickChange].t4h,
#         metrics[:upperWickChange].t8h,

#         metrics[:lowerWickChange].t5m,
#         metrics[:lowerWickChange].t10m,
#         metrics[:lowerWickChange].t15m,
#         metrics[:lowerWickChange].t30m,
#         metrics[:lowerWickChange].t1h,
#         metrics[:lowerWickChange].t2h,
#         metrics[:lowerWickChange].t4h,
#         metrics[:lowerWickChange].t8h,

#         metrics[:upperWickChangeEMA5m].t5m,
#         metrics[:upperWickChangeEMA5m].t10m,
#         metrics[:upperWickChangeEMA5m].t15m,
#         metrics[:upperWickChangeEMA5m].t30m,
#         metrics[:upperWickChangeEMA5m].t1h,
#         metrics[:upperWickChangeEMA5m].t2h,
#         metrics[:upperWickChangeEMA5m].t4h,
#         metrics[:upperWickChangeEMA5m].t8h,

#         metrics[:upperWickChangeEMA30m].t5m,
#         metrics[:upperWickChangeEMA30m].t10m,
#         metrics[:upperWickChangeEMA30m].t15m,
#         metrics[:upperWickChangeEMA30m].t30m,
#         metrics[:upperWickChangeEMA30m].t1h,
#         metrics[:upperWickChangeEMA30m].t2h,
#         metrics[:upperWickChangeEMA30m].t4h,
#         metrics[:upperWickChangeEMA30m].t8h,

#         metrics[:upperWickChangeEMA8h].t5m,
#         metrics[:upperWickChangeEMA8h].t10m,
#         metrics[:upperWickChangeEMA8h].t15m,
#         metrics[:upperWickChangeEMA8h].t30m,
#         metrics[:upperWickChangeEMA8h].t1h,
#         metrics[:upperWickChangeEMA8h].t2h,
#         metrics[:upperWickChangeEMA8h].t4h,
#         metrics[:upperWickChangeEMA8h].t8h,

#         metrics[:lowerWickChangeEMA5m].t5m,
#         metrics[:lowerWickChangeEMA5m].t10m,
#         metrics[:lowerWickChangeEMA5m].t15m,
#         metrics[:lowerWickChangeEMA5m].t30m,
#         metrics[:lowerWickChangeEMA5m].t1h,
#         metrics[:lowerWickChangeEMA5m].t2h,
#         metrics[:lowerWickChangeEMA5m].t4h,
#         metrics[:lowerWickChangeEMA5m].t8h,

#         metrics[:lowerWickChangeEMA30m].t5m,
#         metrics[:lowerWickChangeEMA30m].t10m,
#         metrics[:lowerWickChangeEMA30m].t15m,
#         metrics[:lowerWickChangeEMA30m].t30m,
#         metrics[:lowerWickChangeEMA30m].t1h,
#         metrics[:lowerWickChangeEMA30m].t2h,
#         metrics[:lowerWickChangeEMA30m].t4h,
#         metrics[:lowerWickChangeEMA30m].t8h,

#         metrics[:lowerWickChangeEMA8h].t5m,
#         metrics[:lowerWickChangeEMA8h].t10m,
#         metrics[:lowerWickChangeEMA8h].t15m,
#         metrics[:lowerWickChangeEMA8h].t30m,
#         metrics[:lowerWickChangeEMA8h].t1h,
#         metrics[:lowerWickChangeEMA8h].t2h,
#         metrics[:lowerWickChangeEMA8h].t4h,
#         metrics[:lowerWickChangeEMA8h].t8h,

#         metrics[:upperWickSTD].t5m,
#         metrics[:upperWickSTD].t10m,
#         metrics[:upperWickSTD].t15m,
#         metrics[:upperWickSTD].t30m,
#         metrics[:upperWickSTD].t1h,
#         metrics[:upperWickSTD].t2h,
#         metrics[:upperWickSTD].t4h,
#         metrics[:upperWickSTD].t8h,

#         metrics[:lowerWickSTD].t5m,
#         metrics[:lowerWickSTD].t10m,
#         metrics[:lowerWickSTD].t15m,
#         metrics[:lowerWickSTD].t30m,
#         metrics[:lowerWickSTD].t1h,
#         metrics[:lowerWickSTD].t2h,
#         metrics[:lowerWickSTD].t4h,
#         metrics[:lowerWickSTD].t8h,

#         metrics[:watr].t5m,
#         metrics[:watr].t10m,
#         metrics[:watr].t15m,
#         metrics[:watr].t30m,
#         metrics[:watr].t1h,
#         metrics[:watr].t2h,
#         metrics[:watr].t4h,
#         metrics[:watr].t8h,

#         metrics[:stdWATR5m].t5m,
#         metrics[:stdWATR5m].t10m,
#         metrics[:stdWATR5m].t15m,
#         metrics[:stdWATR5m].t30m,
#         metrics[:stdWATR5m].t1h,
#         metrics[:stdWATR5m].t2h,
#         metrics[:stdWATR5m].t4h,
#         metrics[:stdWATR5m].t8h,
        
#         metrics[:stdWATR30m].t5m,
#         metrics[:stdWATR30m].t10m,
#         metrics[:stdWATR30m].t15m,
#         metrics[:stdWATR30m].t30m,
#         metrics[:stdWATR30m].t1h,
#         metrics[:stdWATR30m].t2h,
#         metrics[:stdWATR30m].t4h,
#         metrics[:stdWATR30m].t8h,
        
#         metrics[:stdWATR8h].t5m,
#         metrics[:stdWATR8h].t10m,
#         metrics[:stdWATR8h].t15m,
#         metrics[:stdWATR8h].t30m,
#         metrics[:stdWATR8h].t1h,
#         metrics[:stdWATR8h].t2h,
#         metrics[:stdWATR8h].t4h,
#         metrics[:stdWATR8h].t8h,

#         metrics[:diffWATR5m].t5m,
#         metrics[:diffWATR5m].t30m,
#         metrics[:diffWATR5m].t1h,
#         metrics[:diffWATR5m].t2h,
#         metrics[:diffWATR5m].t4h,
#         metrics[:diffWATR5m].t8h,
#         metrics[:diffWATR30m].t5m,
#         metrics[:diffWATR30m].t30m,
#         metrics[:diffWATR30m].t1h,
#         metrics[:diffWATR30m].t2h,
#         metrics[:diffWATR30m].t4h,
#         metrics[:diffWATR30m].t8h,
#         metrics[:diffWATR8h].t5m,
#         metrics[:diffWATR8h].t30m,
#         metrics[:diffWATR8h].t1h,
#         metrics[:diffWATR8h].t2h,
#         metrics[:diffWATR8h].t4h,
#         metrics[:diffWATR8h].t8h,

#         metrics[:emaDiffWATR5m].t5m,
#         metrics[:emaDiffWATR5m].t30m,
#         metrics[:emaDiffWATR5m].t1h,
#         metrics[:emaDiffWATR5m].t2h,
#         metrics[:emaDiffWATR5m].t4h,
#         metrics[:emaDiffWATR5m].t8h,
#         metrics[:emaDiffWATR30m].t5m,
#         metrics[:emaDiffWATR30m].t30m,
#         metrics[:emaDiffWATR30m].t1h,
#         metrics[:emaDiffWATR30m].t2h,
#         metrics[:emaDiffWATR30m].t4h,
#         metrics[:emaDiffWATR30m].t8h,
#         metrics[:emaDiffWATR8h].t5m,
#         metrics[:emaDiffWATR8h].t30m,
#         metrics[:emaDiffWATR8h].t1h, 
#         metrics[:emaDiffWATR8h].t2h,
#         metrics[:emaDiffWATR8h].t4h,
#         metrics[:emaDiffWATR8h].t8h]
#     )
# end

# resData = CSV.read("bch_focused1m.csv",DataFrame,stringtype=String)

# select!(calculated1m,Not(:time_added))
# select!(resData,Not(:time_added))

# endM = nrow(calculated1m)

# @testset "DivCalcMetrics.jl" begin

#     for i in 1:endM
#         @test calculated1m[i,:] == resData[i,:]
#     end

# end
